### ISSUE TITLE
Add color input select and automations to  Garage Light Bulbs

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#1]

**Comment by SilvrrGIT** [comment]
1. create new input_select.yaml file
2. Add !include to configuration.yaml for input_select
3. Add automation config to outside_lights.yaml 

```
automation:   
  - alias: Set Garage Bulb Color
    trigger:
      platform: state
      entity_id: input_select.garage_bulb_color
	condition:
	  condition: value_template
	  value_template: "{{ states('input_select.garage_bulb_color') != 'Normal' }}"
    action:
      service: light.turn_on
	  entity_id: group.garage_lights
	  color_name: '{{ states.input_select.garage_bulb_color.state }}'
  
  - alias: Set Garage Bulb Color to Normal
    trigger:
      platform: state
      entity_id: input_select.garage_bulb_color
	condition:
	  condition: value_template
	  value_template: "{{ is_state('input_select.garage_bulb_color', 'Normal') }}"
    action:
      - service: light.turn_on
	    entity_id: group.garage_lights
	    rgb_color: '255,255,255'
      - service: light.turn_on
        entity_id: light.front_porch
        brightness: 255
      - service: light.turn_on
        entity_id: light.back_porch
        brightness: 255			
	  	  
input_select:
  Garage_bulb_color:
    name: Garage Bulb Color
    options:
      - "Normal"
      - "Red"
      - "Orange"
      - "Yellow"
      - "Green"
      - "Blue"
      - "Indigo"
      - "Violet"
      - "Purple"
	icon: mdi:lightbulb
```
