### ISSUE TITLE
Comcast shell?

### ISSUE THREAD

**Issue by poldim** [SilvrrGIT/HomeAssistant#105]
Do you mind sharing some details on what you're doing with Comcast here?

https://github.com/SilvrrGIT/HomeAssistant/blob/2cfd5a997addd3dab64dfd3f9909748f052219b8/configuration.yaml#L182

just found this.........please share the details, I've been looking for this for a while:
```
      - type: entities
        title: Comcast Data Usage
        entities:
          - entity: sensor.comcast_utilization
            name: Used
            icon: mdi:percent
          - entity: sensor.comcast_template
            name: Days Left
          - entity: sensor.comcast_avg_gb_current
            name: Current Daily Avg.
            icon: mdi:chart-line
          - entity: sensor.comcast_avg_gb_left
            name: Remaining Daily Avg.
            icon: mdi:chart-line-stacked
```
