### ISSUE TITLE
Add Start/Stop Automation

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#106]
I think this one will be off most of the time but there are times where it would be useful. 
```
####################################################
#                                                  #
#          HOME ASSISTANT START / STOP             #
#                                                  #
####################################################

  - alias: Home Assistant Started
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.ios_adams_iphone
        data:
          title: "Home Assistant Started"
          message: "Home Assistant Has Started"

  - alias: Home Assistant Stopped
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: notify.ios_adams_iphone
        data:
          title: "Home Assistant Stopped"
          message: "Home Assistant Has Stopped"
```

For Lovlace setup add the following under 

```
      - type: entities
        title: Home Assistant Automations
        show_header_toggle: false
        entities:
          - entity: automation.home_assistant_started
            name: Home Assistant Started
            icon: mdi:home-assistant
          - entity: automation.home_assistant_stopped
            name: Home Assistant Stopped
            icon: mdi:home-assistant
```
