### ISSUE TITLE
Add disk use notification

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#108]
I try to keep my HA disk trim as i don't give it much space during VM setup in ESXi.  Just a quick notification if it starts getting full. 

```
  - alias: "Disk Use Alarm"
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent_
        above: 85
    action:
      service: notify.home_assistant
      data_template:
        title: "Hass.io VM Disk Use Alarm"
        message: "Hass.io VM is running low on disk space, usage is currently at {{ states. sensor.disk_use_percent_home.state }} %!"
```

Also add the following to the automation tab in the HomeAssitant card

```
          - entity: automation.disk_use_alarm
            name: Hass.io VM Disk Use Alarm
            icon: mdi:harddisk
```
