### ISSUE TITLE
Sensor Low Battery Alert Notification

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#126]
I could have sworn that this was in place already but I guess not.  Need to add a notification for when a zwave/zigbee device battery is getting low.  

```
#########################################################
#                                                       #
#                   SENSOR BATTERY LOW                  #
#                                                       #
#########################################################

  - alias: "Low Battery Adams Phone"
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.tradfri_remote_control
          - sensor.gehingepinsensor1batt
          - sensor.gehingepinsensor2batt
          - sensor.garagedoorstatusbatt
          - sensor.backdoorstatusbatt
        below: 20
    action:
      service: notify.home_assistant
      data_template:
        title: "Home Assistant Device Battery Low"
        message: " The battery for {{ trigger.to_state.attributes.friendly_name }} is below 20 percent."

#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
```
