### ISSUE TITLE
Add Find my iphone scripts

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#127]
Find my iphone finally works!  Need to create two scripts and expose them to emulated hue. 

```
script:
  findadamsiphone:
    sequence:
      service: device_tracker.icloud_lost_iphone
      data:
        device_name: adam_siphone

  findamysiphone:
    sequence:
      service: device_tracker.icloud_lost_iphone
      data:
        device_name: amy_siphone
```

```
emulated_hue:
  expose_by_default: false
  entities:
    script.findadamsiphone:
      hidden: false
      name: findadamsiphone
    script.findamysiphone:
      hidden: false
      name: findamysiphone
```

Hopefullly can expose this as a routine so the language is a bit more natural.  ("Alexa, find adams phone" vs. "Alexa, turn on find adams phone")
