### ISSUE TITLE
Setup Input Boolean or MQTT device tracker to combine multiple device trackers

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#130]
Going to do some testing combining multiple trackers.  Going to just send a notification for now.  If this proves to be a better detection method then I will either add an action for an input boolean or a mqtt device tracker. 

```
  - alias: "Combined Away Tracker"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'leave'
      - platform: zone
        entity_id: device_tracker.adams_iphone
        zone: zone.home
        event: 'leave'
      - platform: state
        entity_id:  device_tracker.d81c79eb20c9
        to: 'not_home'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.adams_iphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
    action:
      - service: notify.ios_adams_iphone
        data:
          message: Testing notification
          title: Adam is Away

```

I also want to see which one marks me away first and the most consistently.  

```
logbook:
  include:
    entities:
      - device_tracker.adam_siphone
      - device_tracker.adams_iphone
      - device_tracker.d81c79eb20c9
     - automation.combined_away_tracker
     - automation.combined_home_tracker
```

And I need to have a similar automation for arriving home. 
```
  - alias: "Combined Home Tracker"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'enter'
      - platform: zone
        entity_id: device_tracker.adams_iphone
        zone: zone.home
        event: 'enter'
      - platform: state
        entity_id:  device_tracker.d81c79eb20c9
        to: 'home'
    action:
      - service: notify.ios_adams_iphone
        data:
          message: Testing notification
          title: Adam is Home
```

**Comment by SilvrrGIT** [comment]
Implemented code is as follows: 

```
  - alias: "Combined Away Tracker"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'leave'
      - platform: zone
        entity_id: device_tracker.adams_iphone
        zone: zone.home
        event: 'leave'
      - platform: state
        entity_id:  device_tracker.d81c79eb20c9
        to: 'not_home'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('device_tracker.adam_siphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.adams_iphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.d81c79eb20c9') != 'home' }}"
    action:
      - service: notify.ios_adams_iphone
        data:
          message: Testing notification
          title: Adam is Away
      - service: mqtt.publish
        data:
          topic: location/adam
          payload: not_home


  - alias: "Combined Home Tracker"
    trigger:
      - platform: zone
        entity_id: device_tracker.adam_siphone
        zone: zone.home
        event: 'enter'
      - platform: zone
        entity_id: device_tracker.adams_iphone
        zone: zone.home
        event: 'enter'
      - platform: state
        entity_id:  device_tracker.d81c79eb20c9
        to: 'home'
    condition:
      - condition: template
        value_template: "{{ states('device_tracker.adam') != 'home' }}"
    action:
      - service: notify.ios_adams_iphone
        data:
          message: Testing notification
          title: Adam is Home
      - service: mqtt.publish
        data:
          topic: location/adam
          payload: home
```
