### ISSUE TITLE
Add watchdog for NUT addon

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#133]
Seems like this add-on locks up occasionally.  Adding an automation to monitor the output and restart the add-on should at least put a band-aid on it until I can find a better add-on. 

```
  - alias: "Restart NUT Add On"
    trigger:
      platform: state
      entity_id:  sensor.ups_status
      to: 'unknown'
    action:
      - service: switch.turn_off
        entity_id: switch.nut
      - delay: '00:00:30'
      - service: switch.turn_on
        entity_id: switch.nut
      - service: notify.ios_adams_iphone
        data:
          title: Nut Add-On Watchdog
          message: Nut Add-On was restarted due to a 'unknown' state being reported to Home Assistant
```
