### ISSUE TITLE
Add Water Filter Maintenance Reminder

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#135]
```
  - alias: "Humidifier Maintenance Reminder"
    trigger:
      platform: sun
      event: sunset
    condition:
      condition: or
      conditions: 
        - condition: template
          value_template: '{{ now().strftime("%m-%d") == "04-01" }}'
        - condition: template
          value_template: '{{ now().strftime("%m-%d") == "10-01" }}'
    action:
      service: notify.home_assistant
      data:
        title: "Water Filter Maintenance"
        message: "Check and Replace the water filters.  The are Whirlpool WHEEDF Replacement Filters"
```
