### ISSUE TITLE
Add condition to doorbell automation action

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#137]
Add the below condition to the action section to only flash the light and play the message on alexa when someone is present. 

```
       - condition:
           - condition: template
             value_template: "{{ states('group.home_presence') != 'away' }}"
           - condition: template
             value_template: "{{ states('input_boolean.guest_mode') != 'on' }}"  
```
