### ISSUE TITLE
Update feed the dog automations

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#154]
Current Action section....
``` 
    action:
      - service: automation.turn_off
        entity_id: automation.feed_the_dog_morning
      - service: script.normallight
      - delay: '00:00:01'
      - service: light.turn_off
        entity_id: light.yeelightrgb2
      - service: homeassistant.turn_off
        entity_id: input_boolean.feeddog
```

Planned action section

```
    action:
      - service: automation.turn_off
        entity_id: automation.feed_the_dog_morning
      - service: homeassistant.turn_off
        entity_id: input_boolean.feeddog
      - service_template: >
               {%- if is_state('switch.basic1', 'on') -%}
                 script.normallight
               {%- else -%}
                 script.returntonormal
               {%- endif %}

```
Add a new script also....
```
script:
  retruntonormal:
    sequence:
      - service: script.normallight
      - delay: '00:00:01'
      - service: light.turn_off
        entity_id: light.yeelightrgb2
```
