### ISSUE TITLE
Weather sensors not updating without restart

### ISSUE THREAD

**Issue by gregdelima** [SilvrrGIT/HomeAssistant#156]
Looking at the portion here:
https://github.com/SilvrrGIT/HomeAssistant/blob/master/sensors/weather.yaml#L68 

I loved this portion and for a while it was working great and updating daily. For some reason the templates aren't changing on a daily basis.

I only change a couple items by adding "Hi: / Low: / Precip:" preceeding each reading: 

```
#Darksky Sensors
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_probability
      - temperature_low
      - temperature_high
    scan_interval:
      minutes: 60

  - platform: template
    sensors:
      forecast_0:
        entity_id: []
        friendly_name: "Today"
        value_template: >
          Hi: {{states.sensor.dark_sky_daytime_high_temperature_0d.state|round(0)}}°/ Low: {{states.sensor.dark_sky_overnight_low_temperature_0d.state|round(0)}}°/Precip: {{states.sensor.dark_sky_precip_probability_0d.state|round(0)}}%
```

Seems to be related to: https://community.home-assistant.io/t/template-sensor-not-updating-after-0-81-0/75590
but the blank array of `entity_id: []` should be solving that issue, so not sure if it's a "me problem"
