### ISSUE TITLE
Add Home Maintenance Reminders to HA

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#16]
Below code should work, need to test the template triggers in the dev tool and integrate

```
automation:

  - alias: Trash Day Reminder  
    trigger:
      platform: time
      at: '18:00:00'
    condition:
      condition: time
      weekday:
        - mon
    action:
      service: notify.home_assistant
      data:
        title: "Today Is Trash Day"
        message: "Take the trash and recycling to the curb"
	  
  - alias: "Furnace Filter Reminder"
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%d") == "1" }}'
    action:
      service: notify.home_assistant
      data:
        title: "Check Furnace Filter and Replace if Needed"
        message: "Furnace filter is 16x25x1 if you need to buy one"
		
  - alias: "Belle Flea, Tick and Heartworm Reminder"
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%d") == "15" }}'
    action:
      service: notify.home_assistant
      data:
        title: "Belle Reminder"
        message: "Give Belle heartworm pill and apply flea and tick treatment"
		
  - alias: "Water Softener Reminder"
    trigger:
      - platform: template
        value_template: '{{ now().strftime("%d") == "25" }}'
    action:
      service: notify.home_assistant
      data:
        title: "Check Water Softener Salt Level"
```
