### ISSUE TITLE
Reduce outside light brightness and automate increase when doors open

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#17]
Set a lower light level for all lights by default at sunset.  Then when a door opens (garage door or front door), increase the light level until that door closes.  use the timeout of the wait function to dim the lights after a period of time (used in the summer when we may have doors open to let the breeze in)

**Comment by SilvrrGIT** [comment]
Config to test and implement.

```

#########################################################
#                                                       #
#          TURN OFF OUTSIDE LIGHTS AT SUNRISE           #
#                                                       #
#########################################################

  - alias: 'Turn Off Outside Lights'
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: homeassistant.turn_off
        entity_id: group.outside_lights

#########################################################
#                                                       #
#           TURN ON OUTSIDE LIGHTS AT SUNSET            #
#                                                       #
#########################################################

  - alias: 'Turn On Outside Lights'
    trigger:
      platform: sun
      event: sunset
      offset: '-00:15:00'
    action:
      - service: light.turn_on
        data:
		  entity_id:          
		    - light.yeelight1
			- light.yeelight2
			- light.yeelight3
            - light.yeelight4
		  brightness_pct: 33
		  
#########################################################
#                                                       #
#          OPEN FRONT DOORS INCREASE BRIGHTNESS         #
#                                                       #
#########################################################

  - alias: "Open Front Doors Increase Brightness"
    trigger:
      - platform: state
        entity_id: 
		  - sensor.gehingepinsensor1
		  - sensor.garagedoorstatus
        from: 'Closed'
        to: 'Open'
    condition:
      condition: state
      entity_id: group.outside_lights
      state: 'On'
    action:
      - service: light.turn_on
        data:
		  entity_id: 
		    - light.yeelight1
			- light.yeelight2
			- light.yeelight3
		  brightness: 254
      - wait_template: "{{ is_state(trigger.entity_id, 'Closed') }}"
      - service: light.turn_on
        data:
		  entity_id: 
		    - light.yeelight1
			- light.yeelight2
			- light.yeelight3
		  brightness_pct: 33
          
#########################################################
#                                                       #
#            OPEN BACK DOOR INCREASE BRIGHTNESS         #
#                                                       #
#########################################################

  # - alias: "Open Back Door Increase Brightness"
    # trigger:
      # - platform: state
        # entity_id: 
		  # - sensor.futuredoorsensor
        # from: 'Closed'
        # to: 'Open'
    # condition:
      # condition: state
      # entity_id: group.outside_lights
      # state: 'On'
    # action:
      # - service: light.turn_on
        # data:
		  # entity_id: light.yeelight4
		  # brightness: 254
      # - wait_template: "{{ is_state(trigger.entity_id, 'Closed') }}"
      # - service: light.turn_on
        # data:
		  # entity_id: light.yeelight4
		  # brightness_pct: 33
          
#########################################################
#                                                       #
#            END OF CONFIGURATION FILE                  #
#                                                       #
#########################################################
```
