### ISSUE TITLE
Add Radar Map to HVAC Tab

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#2]
1.  add config below to camera.yaml
2.  add "camera.radar" to HVAC View group
3. Update config files
4. Update HVAC readme.md image

```
camera:
  platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=LOT&brand=wui&num=1&delay=15&type=N0R&frame=0&scale=1.000&noclutter=1&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=1&lightning=0&smooth=1&rand=24970615&lat=0&lon=0&label=you
  name: Radar
```
