### ISSUE TITLE
Switch "Devices" group in Device Status tab to Ping Binary Sensor

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#22]
The custom binary sensor component I am currently using is the last remaining custom component I have.  For easy of maintenance and future compatibility it seems to make sense to move to an 'official' component.  

https://home-assistant.io/components/binary_sensor.ping/

**Comment by SilvrrGIT** [comment]
```
binary_sensor:
  - platform: ping
    host: 192.168.1.23
    name: Linux Laptop
  - platform: ping
    host: 192.168.100.1
    name: Modem
  - platform: ping
    host: 192.168.1.50
    name: Netgear Router
  - platform: ping
    host: 192.168.2.2
    name: NAS
  - platform: ping
    host: 192.168.1.19
    name: Netgear Switch
  - platform: ping
    host: 192.168.1.13
    name: Canon Printer
  - platform: ping
    host: 192.168.1.30
    name: Raspberry Pi 3 Wifi
  - platform: ping
    host: 192.168.1.22
    name: Raspberry Pi Zero W
  - platform: ping
    host: 192.168.1.31
    name: Raspberry Pi 3 Wired
  - platform: ping
    host: 192.168.1.14
    name: Raspberry Pi 2 Wired
  - platform: ping
    host: 192.168.1.15
    name: Edimax Wifi USB
```

**Comment by SilvrrGIT** [comment]
```
group:
  Devices:
    - binary_sensor.linux_laptop
    - binary_sensor.modem
    - binary_sensor.netgear_router
    - binary_sensor.NAS
    - binary_sensor.netgear_switch
    - binary_sensor.canon_printer
    - binary_sensor.raspberry_pi_3_wifi
    - binary_sensor.raspberry_pi_zero_w
    - binary_sensor.raspberry_pi_3_wired
    - binary_sensor.raspberry_pi_2_wired
    - binary_sensor.edimax_wifi_usb
```

**Comment by SilvrrGIT** [comment]
```
customize:
binary_sensor.linux_laptop:
  icon: mdi:linux

binary_sensor.modem:
  icon: mdi:server-network

binary_sensor.netgear_router:
  icon: mdi:router-wireless

binary_sensor.NAS:
  icon: mdi:harddisk

binary_sensor.netgear_switch:
  icon: mdi:switch

binary_sensor.canon_printer:
  icon: mdi:printer

binary_sensor.raspberry_pi_3_wifi:
  friendly_name: Raspberry Pi 3 (Wifi)
  icon: mdi:raspberrypi

 binary_sensor.raspberry_pi_zero_w:
  icon: mdi:raspberrypi

 binary_sensor.raspberry_pi_3_wired:
  friendly_name: Raspberry Pi 3 (Wired)
  icon: mdi:raspberrypi

 binary_sensor.raspberry_pi_2_wired:
  friendly_name: Raspberry Pi 3 (Wired)
  icon: mdi:raspberrypi

 binary_sensor.edimax_wifi_usb:
  icon: mdi:usb
```
