### ISSUE TITLE
Add link to New Device ID automation to include link to MAC lookup Site

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#26]
Small addition to this automation to include a hyperlink to a MAC lookup site to determine what the new device is.  

https://aruljohn.com/mac.pl is a site to look up the mfg.

The failed login IP lookup can be used for inspration:
```
    action:
      - service: notify.home_assistant
        data_template:
          title: "{{ states.persistent_notification.httplogin.attributes.message }}"
          message: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.httplogin.attributes.message.split ("from ") [1]}}'
```
