### ISSUE TITLE
Clean Up Sensors File

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#35]
Either delete these or get them working again
```
#https://home-assistant.io/components/sensor.command_line/
  # -  platform: command_line
  #    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  #    name: Current HA Version
  #
  # -  platform: command_line
  #    name: Installed version
  #    command: "head -5 /home/ha/.homeassistant/.HA_VERSION"
```

Delete these, no longer used
```
#https://home-assistant.io/components/sensor.template/
  - platform: template
    sensors:
      adamwifi:
        value_template: '{% if is_state("device_tracker.bc9fef3f3205", "home") %}Online{% else %}Offline{% endif %}'

      amywifi:
        value_template: '{% if is_state("device_tracker.bc9fef2f1fe3", "home") %}Online{% else %}Offline{% endif %}'
```

Make this report on or off.  Currently its on/false
```
#https://home-assistant.io/components/sensor.template/
  - platform: template
    sensors:
     downstairs_away_mode:
       value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"
```

Bring cert expiry sensor and automation back
```
#https://home-assistant.io/components/sensor.cert_expiry/
  # - platform: cert_expiry
  #   host: !secret host
  #   port: 8123
  #   name: Lets Encrypt Expiration
```
