### ISSUE TITLE
Detect if Amplifier or TV is left On

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#37]
My TV and amplifier are old and although controlled by the broadlink IR component the state isn't reported. I think it should be easy to figure which device is on based on the power draw.  

```
  - alias: "Media Center On When leaving"
    trigger:
      - platform: zone
        entity_id: device_tracker.adamsiphone
        zone: zone.home
        event: 'leave'
      - platform: zone
        entity_id: device_tracker.amysiphone
        zone: zone.home
        event: 'leave'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states.sensor.edimax2_watts | float > 10 }}"
        - condition: template
          value_template: "{{ states('device_tracker.amysiphone') != 'home' }}"
        - condition: template
          value_template: "{{ states('device_tracker.adamsiphone') != 'home' }}"
```

**Comment by SilvrrGIT** [comment]
Nothing on = 7 watts
TV on =  135 watts
Amplifier on = 55 watts

**Comment by SilvrrGIT** [comment]
```
    action:
      - service: notify.ios_adams_iphone
        data_tempalte:
          message: "The Media Center is pulling {{ states.sensor.edimax2_watts }} watts and you are gone  "
            data:
              push:
                badge: 0
                category: 'mediacenter'
```

For ios.yaml

```
      - name: Media Center
        identifier: 'mediacenter'
        actions:
          - identifier: 'TV_OFF'
            title: 'TV Off'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'RECEIVER_OFF'
            title: 'Receiver Off'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: no
            behavior: 'default'
```
Automation yaml file for action automations.

```
  - alias: TV on when away notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: TV_OFF
    action:
      - service: switch.turn_off
        entity_id: switch.tvpower

  - alias: Receiver on when away notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: RECEIVER_OFF
    action:
      - service: switch.turn_off
        entity_id: switch.receiverpower
```
