### ISSUE TITLE
Update edimax sensors to render 0 when a value isn't provided

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#38]
These currently report unknown when the bulb is off (watts) or has been off since midnight (KWh).  I would like them to report 0.  

```
      edimax1_watts:
        value_template: '{% if states.switch.edimax1.attributes %}{{ states.switch.edimax1.attributes["current_power_w"] | round(2) }}{% endif %}'
        unit_of_measurement: 'W'

      edimax1_kwh:
        value_template: '{% if states.switch.edimax1.attributes %}{{ states.switch.edimax1.attributes["today_energy_kwh"] | round(2) }}{% endif %}'
        unit_of_measurement: 'kWh'

      edimax1_cost:
        value_template: '{% if states.switch.edimax1.attributes %}{{ states("sensor.edimax1_kwh") | round  (2) |  float * 16 }}{% endif %}'
        unit_of_measurement: '¢'

      edimax2_watts:
        value_template: '{% if states.switch.edimax2.attributes %}{{ states.switch.edimax2.attributes["current_power_w"] | round(2) }}{% endif %}'
        unit_of_measurement: 'W'

      edimax2_kwh:
        value_template: '{% if states.switch.edimax2.attributes %}{{ states.switch.edimax2.attributes["today_energy_kwh"] | round(2) }}{% endif %}'
        unit_of_measurement: 'kWh'

```
