### ISSUE TITLE
Remote Switch Activation acts on all switches

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#4]
The command line switch platform is used to turn on the switches in my remote instance.  However when any switch in the main instance is turned on all the switches in the remote instance turn on.  

Code used is pasted below:

```
  - platform: command_line
    switches:

      rfswitch1:
        command_on: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_on?{"entity_id":"switch.rfswitch1"}
        command_off: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_off?{"entity_id":"switch.rfswitch1"}
        command_state: /usr/bin/curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch1
        value_template: '{{ value_json.state == "on" }}'
   
      rfswitch2:
        command_on: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_on?{"entity_id":"switch.rfswitch2"}
        command_off: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_off?{"entity_id":"switch.rfswitch2"}
        command_state: /usr/bin/curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch2
        value_template: '{{ value_json.state == "on" }}'
        
      rfswitch3:
        command_on: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_on?{"entity_id":"switch.rfswitch3"}
        command_off: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_off?{"entity_id":"switch.rfswitch3"}
        command_state: /usr/bin/curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch3
        value_template: '{{ value_json.state == "on" }}'
        
      rfswitch4:
        command_on: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_on?{"entity_id":"switch.rfswitch4"}
        command_off: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_off?{"entity_id":"switch.rfswitch4"}
        command_state: /usr/bin/curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch4
        value_template: '{{ value_json.state == "on" }}'

      rfswitch5:
        command_on: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_on?{"entity_id":"switch.rfswitch5"}
        command_off: /usr/bin/curl -X POST http://192.168.1.30:8123/api/services/switch/turn_off?{"entity_id":"switch.rfswitch5"}
        command_state: /usr/bin/curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch5
        value_template: '{{ value_json.state == "on" }}'
```

**Comment by SilvrrGIT** [comment]
As expected the formatting is incorrect.  The api is seeing the light.turn on command before it even evaluates which device to turn on.  Therefore all switches turn on.  Updated code to try below.


```
  rfswitch1:
    command_on: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch1"}' \http://192.168.1.30:8123/api/services/switch/turn_on
    command_off: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch1"}' \http://192.168.1.30:8123/api/services/light/turn_off
    command_state: curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch1
    value_template: '{{ value_json.state == "on" }}'

  rfswitch2:
    command_on: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch2"}' \http://192.168.1.30:8123/api/services/switch/turn_on
    command_off: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch2"}' \http://192.168.1.30:8123/api/services/light/turn_off
    command_state: curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch2
    value_template: '{{ value_json.state == "on" }}'

  rfswitch3:
    command_on: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch3"}' \http://192.168.1.30:8123/api/services/switch/turn_on
    command_off: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch3"}' \http://192.168.1.30:8123/api/services/light/turn_off
    command_state: curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch3
    value_template: '{{ value_json.state == "on" }}'

  rfswitch4:
    command_on: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch4"}' \http://192.168.1.30:8123/api/services/switch/turn_on
    command_off: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch4"}' \http://192.168.1.30:8123/api/services/light/turn_off
    command_state: curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch4
    value_template: '{{ value_json.state == "on" }}'

  rfswitch5:
    command_on: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch5"}' \http://192.168.1.30:8123/api/services/switch/turn_on
    command_off: curl -X POST -H "x-ha-access:" \-H "Contentype:application/json" \-d '{"entity_id":"switch.rfswitch5"}' \http://192.168.1.30:8123/api/services/light/turn_off
    command_state: curl -X GET http://192.168.1.30:8123/api/states/switch.rfswitch5
    value_template: '{{ value_json.state == "on" }}'
```
