### ISSUE TITLE
Adjust Device offline automation to use yeelight state

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#40]
https://github.com/SilvrrGIT/HomeAssistant/blob/master/automation/deviceoffline.yaml

The yeelights will report unavailable if they go offline.  This can be used as its already available and lower some of the ping traffic on the network.  

```
  - alias: "Notify if Yeelight Offline"
    trigger:
      - platform: state
        entity_id:
          - light.yeelight_1
          - light.yeelight_2
          - light.yeelight_3
          - light.yeelight_4
          - light.yeelight_5
          - light.yeelight_rgb_2
        to: 'unavailable'
    action:
      service: notify.home_assistant
      data_template:
        title: "Yeelight is Offline"
        message: "{{ trigger.to_state.attributes.friendly_name }} is offline"
```
