### ISSUE TITLE
Desktop Security Automation not firing

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#53]
I noticed this automation isn't firing.  

https://github.com/SilvrrGIT/HomeAssistant/blob/master/automation/pc_security.yaml#L16

Need to change the condition from:

```
    condition:
        condition: state
        entity_id: 'device_tracker.adamsiphone'
        state: 'not_home'
```

to something more like
```
        - condition: template
          value_template: "{{ states('device_tracker.adamsiphone') != 'home' }}"
```

I think the 'not_home' is no longer applicable as 'away' or a zone name are used.
