### ISSUE TITLE
Update Nest Automation to avoid changing for the seasons

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#64]
I currently have to manually change the yaml to adjust for the seasons (heat in winter vs. cool in summer)

This provided a good idea for accomplishing making this automatic and allowing adjustments from the thermostat.

https://community.home-assistant.io/t/error-taking-nest-out-of-eco-mode/48843/8?u=silvrr

To Do:

1. Add a input text
```
input_text:
  nest_mode:
    name: Heating/Cooling Mode
```

2. Adjust the action for "Set Nest Away Mode When Leaving" to:

```
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nest_mode
        value: '{{ states.climate.house_nest.attributes.operation_mode }}'
    - service: climate.set_operation_mode
      data:
        entity_id: climate.house_nest
        operation_mode: 'eco'
    - service: climate.set_away_mode
      data:
        entity_id: climate.downstairs
        away_mode: 'true'
```

3. Adjust the action for "Set Nest Away Mode at 1600" to:
```
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'false'
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.house_nest
          operation_mode: '{{ states.input_text.nest_mode.state }}'
```

4. Adjust the action for "Turn Off Away When Home" to:

```
    action:
      - service: climate.set_away_mode
        data:
          entity_id: climate.downstairs
          away_mode: 'false'
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.house_nest
          operation_mode: '{{ states.input_text.nest_mode.state }}'
```
