### ISSUE TITLE
Simplify Low Battery Notification

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#69]
Not sure how I missed the zone condition in the past.  

Update the automation here:
https://github.com/SilvrrGIT/HomeAssistant/blob/master/automation/low_battery_adam_phone.yaml#L15

To:

```
  - alias: "Low Battery Adams Phone"
    trigger:
      - platform: numeric_state
        entity_id: sensor.battery_adamsiphone
        below: 50
      - platform: numeric_state
        entity_id: sensor.battery_adamsiphone
        below: 30
    condition:
      condition: zone
      entity_id: device_tracker.adamsiphone
      zone: zone.adam_work
    action:
      service: notify.ios_adams_iphone
      data:
        title: "Your Battery is low, charge your phone!"
        message: "Adam's iPhone battery is getting low and should be charged"
```
