### ISSUE TITLE
Entertainment Center Scripts

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#7]
```
####################################################
#                                                  #
#             Turn Off Media Center                #
#                                                  #
####################################################
##For Script.yaml file

mediacenteroff:
    alias: Media Center
    sequence:
      - service: homeassistant.turn_off
        entity_id: switch.htpc_switch
      - service: homeassistant.turn_off
        entity_id: switch.edimax1
      - service: homeassistant.turn_off
        entity_id: switch.edimax2

 ##For customize.yaml file

    script.mediacenteroff:
      emulated_hue: true
      emulated_hue_name: "Media Center"
```
