### ISSUE TITLE
Change Input_Text to Input_Select for HVAC mode automations

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#71]
Input_text is not persistent across restarts and causes and issue if I forget to set it after a restart.  An Input_Select will persist and should be an easy solution. 

1. create input select and remove input text.
```
input_select:
  nestmode:
    name: Nest Mode
    options:
     - heat
     - cool
     - eco
```

2. Revise Nest.yaml automation file to incorporate change. 

```
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.nestmode
          value: '{{ states.climate.downstairs.attributes.operation_mode }}'

```

and 

```
      - service: climate.set_operation_mode
        data_template:
          entity_id: climate.downstairs
          operation_mode: '{{ states.input_select.nestmode.state }}'
```

**Comment by SilvrrGIT** [comment]
it appears option is the correct use with input select

```
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.nestmode
          option: '{{ states.climate.downstairs.attributes.operation_mode }}'
````
