### ISSUE TITLE
Error in thermostat automation

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#95]
```
    action:
      - service: climate.temperature
        data:
          entity_id: climate.linear_heating
          temperature: 69
```
The above service call is incorrect.  Correct to:

```
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.linear_heating
          temperature: 69
```
