### ISSUE TITLE
add scan interval to Github sensor.

### ISSUE THREAD

**Issue by SilvrrGIT** [SilvrrGIT/HomeAssistant#98]
Hitting this API way to often, thought I configured this but apparently not. 

https://github.com/SilvrrGIT/HomeAssistant/blob/master/sensors/github.yaml#L12
```
  - platform: command_line
    command: 'curl https://api.github.com/repos/silvrrgit/homeassistant'
    name: github
   scan_interval: 3600
    value_template: '{{ value_json.name }}'
    json_attributes:
      - open_issues
      - subscribers_count
      - forks
      - stargazers_count
```
